In [1]:
!gdown 1RIzuzTcoGa0JAk_1s4IdgZkQuVfDkRO6

Downloading...
From: https://drive.google.com/uc?id=1RIzuzTcoGa0JAk_1s4IdgZkQuVfDkRO6
To: /content/books.csv
100% 72.8M/72.8M [00:00<00:00, 164MB/s]


In [2]:
import numpy
import pandas as pd
from pandas import DataFrame

In [3]:
data = pd.read_csv("books.csv")

In [4]:
desc=data['description'].tolist()

In [5]:
print(len(desc))

23665


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
vectorizer = CountVectorizer()

In [9]:
vectorizer.fit(desc)

CountVectorizer()

In [10]:
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'do': 11638, 'you': 42273, 'like': 22856, 'to': 38213, 'play': 29116, 'in': 19454, 'exploration': 14229, 'lite': 23001, 'this': 37897, 'application': 3152, 'is': 20416, 'useful': 39728, 'for': 15477, 'players': 29128, 'of': 27136, 'whatever': 41514, 'level': 22628, 'look': 23236, 'the': 37745, 'best': 5320, 'practices': 29643, 'tipscheats': 38139, 'game': 16187, 'recommendations': 31382, 'free': 15738, 'were': 41453, 'all': 2237, 'those': 37911, 'that': 37739, 'are': 3394, 'presented': 29870, 'today': 38233, 'on': 27340, 'internet': 20183, 'guide': 17537, 'solves': 35202, 'difficulty': 11149, 'users': 39742, 'with': 41796, 'them': 37767, 'have': 17983, 'cope': 9274, 'both': 6160, 'amateur': 2425, 'and': 2590, 'experienced': 14172, 'gamer': 16215, 'win': 41699, 'developed': 10889, 'by': 6659, 'andrzj': 2645, 'homiak': 18663, 'version': 40331, 'where': 41536, 'not': 26600, 'allowed': 2282, 'save': 33252, 'payed': 28298, 'can': 6836, 'personally': 28638, 'feel': 14802, 'dev'

In [12]:
desc_embedding = vectorizer.transform(desc)

In [14]:
print(desc_embedding)

  (0, 2237)	1
  (0, 2282)	1
  (0, 2425)	1
  (0, 2533)	1
  (0, 2590)	2
  (0, 2645)	1
  (0, 3084)	2
  (0, 3152)	1
  (0, 3394)	2
  (0, 4157)	1
  (0, 4907)	1
  (0, 5320)	2
  (0, 5753)	1
  (0, 6160)	1
  (0, 6659)	2
  (0, 6836)	1
  (0, 8529)	1
  (0, 9041)	1
  (0, 9274)	1
  (0, 9287)	2
  (0, 9562)	1
  (0, 9572)	1
  (0, 10881)	1
  (0, 10889)	1
  (0, 11149)	1
  :	:
  (23664, 34800)	1
  (23664, 35396)	1
  (23664, 35592)	2
  (23664, 35773)	4
  (23664, 35903)	1
  (23664, 36328)	1
  (23664, 36357)	1
  (23664, 37618)	1
  (23664, 37745)	16
  (23664, 37760)	1
  (23664, 37897)	2
  (23664, 37945)	1
  (23664, 38213)	4
  (23664, 38599)	2
  (23664, 40508)	1
  (23664, 40672)	1
  (23664, 41089)	1
  (23664, 41207)	3
  (23664, 41566)	1
  (23664, 41685)	1
  (23664, 41796)	9
  (23664, 41926)	1
  (23664, 42034)	2
  (23664, 42273)	3
  (23664, 42290)	3


In [13]:
print(desc_embedding.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
sum=data['summary'].tolist()
name=data['name'].tolist()

In [16]:
vectorizer.fit(sum)
sum_embedding = vectorizer.transform(sum)
print(sum_embedding)
print(sum_embedding.toarray())

  (0, 3753)	1
  (0, 10146)	1
  (0, 11035)	1
  (0, 12456)	1
  (0, 16268)	1
  (1, 1838)	1
  (1, 9263)	2
  (1, 11222)	1
  (1, 11321)	2
  (1, 19217)	1
  (1, 25048)	2
  (1, 26972)	2
  (1, 27248)	1
  (2, 3753)	1
  (2, 11035)	1
  (2, 20598)	1
  (2, 26928)	1
  (2, 28874)	1
  (2, 29951)	1
  (3, 2741)	1
  (3, 3872)	1
  (3, 13796)	1
  (3, 16253)	1
  (3, 17710)	1
  (3, 19339)	1
  :	:
  (23663, 27835)	2
  (23663, 27939)	2
  (23663, 28006)	2
  (23663, 28009)	1
  (23663, 28017)	1
  (23663, 28026)	1
  (23663, 28217)	1
  (23663, 28432)	1
  (23663, 28522)	1
  (23663, 28557)	1
  (23663, 28732)	1
  (23663, 28950)	1
  (23663, 29008)	1
  (23663, 29057)	1
  (23663, 29080)	1
  (23663, 29241)	2
  (23663, 29282)	1
  (23663, 29438)	6
  (23663, 29516)	9
  (23663, 29526)	2
  (23663, 29549)	1
  (23663, 29758)	1
  (23663, 29768)	3
  (23664, 14761)	1
  (23664, 25314)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
vectorizer.fit(name)
name_embedding = vectorizer.transform(name)
print(name_embedding)
print(name_embedding.toarray())

  (0, 956)	1
  (0, 1185)	1
  (0, 1633)	1
  (1, 891)	1
  (1, 2582)	1
  (1, 2837)	1
  (2, 2151)	1
  (2, 2793)	1
  (2, 2984)	1
  (2, 3132)	1
  (3, 227)	1
  (3, 330)	1
  (3, 916)	1
  (3, 2003)	1
  (4, 330)	1
  (4, 773)	1
  (4, 1197)	1
  (4, 1295)	1
  (5, 227)	1
  (5, 330)	1
  (5, 2318)	1
  (5, 2928)	1
  (6, 227)	1
  (6, 388)	1
  (6, 1058)	1
  :	:
  (23657, 1948)	1
  (23658, 73)	1
  (23658, 2223)	1
  (23658, 2370)	1
  (23659, 50)	1
  (23659, 479)	1
  (23659, 494)	1
  (23659, 601)	1
  (23659, 2614)	1
  (23660, 169)	1
  (23660, 479)	1
  (23660, 1192)	1
  (23660, 1629)	1
  (23660, 1647)	1
  (23660, 2187)	1
  (23660, 2223)	1
  (23661, 1185)	1
  (23661, 2152)	1
  (23662, 222)	1
  (23662, 1270)	1
  (23662, 3080)	1
  (23663, 760)	1
  (23663, 2223)	1
  (23664, 1443)	1
  (23664, 2605)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
